name: Deploy

on:
  push:

jobs:
  deploy:
    permissions:
      id-token: write
      packages: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/cache@v4
      id: cache
      with:
        path: |
          var-cache-apt
          var-lib-apt
        key: cache-${{ hashFiles('Dockerfile') }}

    - uses: reproducible-containers/buildkit-cache-dance@5b6db76d1da5c8b307d5d2e0706d266521b710de # v3.1.2
      with:
        cache-map: |
          {
            "var-cache-apt": "/var/cache/apt",
            "var-lib-apt": "/var/lib/apt"
          }
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}

    - uses: docker/setup-buildx-action@v3

    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/835576187843/locations/global/workloadIdentityPools/wsh2025/providers/github-actions
        service_account: wsh2025@akimon658.iam.gserviceaccount.com

    - uses: google-github-actions/setup-gcloud@v2

    - run: gcloud compute instances update-container wsh2025 --zone us-west1-a --container-image ghcr.io/${{ github.repository }}:${{ github.sha }}
